AdminVivienda/Controllers/Catalogos/CondominioController.cs
using AdminVivienda.BL;
using AdminVivienda.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminVivienda.Controllers.Catalogos
{
    public class CondominioController : Controller
    {
        private CondominioBusiness _condominioBusiness;
        public CondominioController()
        {
            _condominioBusiness = new CondominioBusiness();
        }
        // GET: Condominio
        public ActionResult Index()
        {
            ViewBag.Title = "Buscar condominio";
            return View();
        }

        // GET: Condominio/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.Accion = "Actualizar";
            ViewBag.Title = "Editar condominio";
            var resul = _condominioBusiness.ConsultarId(id);
            return View("~/Views/Condominio/Condominio.cshtml",(AdminVivienda.DAL.CAT_CONDOMINIO)resul.datos);
        }

        // GET: Condominio/Create
        public ActionResult Create()
        {
            ViewBag.Accion = "Agregar";
            ViewBag.Title = "Agregar condominio";
            AdminVivienda.DAL.CAT_CONDOMINIO condominio = new DAL.CAT_CONDOMINIO();
            return View("~/Views/Condominio/Condominio.cshtml", condominio);
        }
        public PartialViewResult Grid(CondominioModel modelo)
        {
            var resul = _condominioBusiness.Consultar(modelo);
            return PartialView("~/Views/Condominio/CondominioGrid.cshtml", (List<AdminVivienda.DAL.CAT_CONDOMINIO>)resul.datos);
        }
        // POST: Condominio/Create
        //[HttpPost]
        //public ActionResult Obtain(CondominioModel modelo)
        //{
        //    var resul = _condominioBusiness.Obtener(modelo);
        //    return Json(resul);
        //}

        // POST: Condominio/Create
        [HttpPost]
        public ActionResult Create(CondominioModel modelo)
        {
            var resul = _condominioBusiness.Agregar(modelo);
            return Json(resul);
        }

        // GET: Condominio/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    var resul = _condominioBusiness.ObtenerPorID(id);
        //    return Json(resul);
        //}

        // POST: Condominio/Edit/5
        [HttpPost]
        public ActionResult Edit(CondominioModel modelo)
        {
            var resul = _condominioBusiness.Actualizar(modelo);
            return Json(resul);
        }
        [HttpPost]
        public ActionResult Select()
        {
            var resul = _condominioBusiness.Select();
            return Json(resul);
        }
        // GET: Condominio/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: Condominio/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

AdminVivienda/Controllers/Catalogos/EstadosController.cs
using AdminVivienda.Models.Catalogos.General;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminVivienda.Controllers.Catalogos
{
    public class EstadosController : CatalogoNivel1Controller
    {
        // GET: TipoVivienda
        private static TablaNivel1 _tablaNivel1 = new TablaNivel1()
        {
            descripcion = "Estado",
            idNombre = "Id_Estado",
            nombreTabla = "CAT_ESTADOS"
        };
        private static Nivel1RecursosModel _nivel1 = new Nivel1RecursosModel()
        {
            campo1 = "Estado",
            maxValue = 50,
            estatus = "Estatus",
            tituloAgregar = "Agregar Estado",
            tituloEditar = "Editar Estado",
            tituloIndex = "Buscar Estado",
            tabla = _tablaNivel1
        };
        public EstadosController() : base(_nivel1)
        {
        }
    }
}

AdminVivienda/Views/Condominio/Condominio.cshtml
@model AdminVivienda.DAL.CAT_CONDOMINIO
<h3 class="header">@ViewBag.Title</h3>
<hr />
<div class="row">
    <div class="input-field col s6 m4 l4">
        <label for="txtcondominio">Condominio *:</label>
        <input type="text" id="txtcondominio" maxlength="100" value="@Model.Condominio">
        <div style="display:none" class="invalid-feedback">Campo Requerido</div>
    </div>
    <div class="input-field col s6 m4 l4">
        <label for="txtclave">Clave *:</label>
        <input type="text" id="txtclave" maxlength="5" value="@Model.Clave">
        <div style="display:none" class="invalid-feedback">Campo Requerido</div>
    </div>
    <div class="input-field col s6 m4 l4">
        <select id="ddlEstado">
            <option selected="" value="-1">Seleccionar</option>
        </select>
        <label>Estado*:</label>
        <div style="display:none" class="invalid-feedback">Campo Requerido</div>
    </div>
    <div class="input-field col s6 m4 l4">
        <label for="txtdemmun">Municipio / Demarcación *:</label>
        <input type="text" id="txtdemmun" maxlength="50" value="@Model.DemMun">
        <div style="display:none" class="invalid-feedback">Campo Requerido</div>
    </div>
    <div class="input-field col s6 m4 l4">
        <label for="txtcolonia">Colonia *:</label>
        <input type="text" id="txtcolonia" maxlength="50" value="@Model.Colonia">
        <div style="display:none" class="invalid-feedback">Campo Requerido</div>
    </div>
    <div class="input-field col s6 m4 l4">
        <label for="txtcp">CP *:</label>
        <input type="number" id="txtcp" maxlength="5" value="@Model.Cp">
        <div style="display:none" class="invalid-feedback">Campo Requerido</div>
    </div>
    @if (ViewBag.Accion == "Actualizar")
    {
        <div class="col s6 m6 l6">
            <label>Estatus:</label>
            <div class="switch">
                <label>
                    Inactivo
                    @if (Model.Activo)
                    {
                        <input type="checkbox" id="chkActivo" checked="">
                    }
                    else
                    {
                        <input type="checkbox" id="chkActivo">
                    }
                    <span class="lever"></span>
                    Activo
                </label>
            </div>
        </div>
    }
</div>
<hr />

<div class="row">
    <p><small class="form-text text-muted">* Campos Obligatorios.</small></p>
    <div class="col s6 m6 l6" align="left">

        <a href="@Url.Action("Index")" class="waves-effect waves-light btn red"><i class="material-icons left">keyboard_return</i>Regresar</a>
    </div>
    <div class="col s6 m6 l6" align="right">
        @if (ViewBag.Accion == "Actualizar")
        {
            <button id="btnActualizar" type="button" class="waves-effect waves-light btn"><i class="material-icons left">autorenew</i>Actualizar</button>
        }
        else
        {

            <button id="btnGuardar" type="button" class="waves-effect waves-light btn"><i class="material-icons left">save</i>Guardar</button>


        }
    </div>
</div>
@section scripts{
    <script>
            var _accion = '@ViewBag.Accion'
        $('#btnGuardar').click(function () {
                 if (fncCamposRequeridos()) {
                return;
            }
                var modelo = ObtenerModelo();
                FncExeAjax('@Url.Action("Create")', modelo, "POST", false, FncLimpiar);
        });
        function FncLimpiar(respuesta) {
            if (respuesta.ejecucion) {
                $('#txtcondominio').val("");
            }
            MsnShow(respuesta);
        }
        function fncCamposRequeridos() {
            var campos = false;
            if ($('#txtcondominio').val() == "") {
                $('#divCondominio').addClass("has-danger");
                var input = $('#divCondominio').find(".form-control");
                $(input[0]).addClass("is-invalid");
                var label = $('#divCondominio').find(".invalid-feedback");
                $(label).show();
                campos = true;
            }
            else {
                $('#divCondominio').removeClass("has-danger");
                var input = $('#divCondominio').find(".form-control");
                $(input[0]).removeClass("is-invalid");
                var label = $('#divCondominio').find(".invalid-feedback");
                $(label).hide();
            }
            return campos;
        }
        $('#btnActualizar').click(function () {
            if (fncCamposRequeridos()) {
                return;
            }
                var modelo = ObtenerModelo();
                FncExeAjax('@Url.Action("Edit")', modelo, "POST", false, MsnShow);
            });
            function ObtenerModelo() {
                var modelo = new Object();
                if (_accion == 'Actualizar') {
                    modelo.Activo = $('#chkActivo').is(":checked") ? 1 : 0;
                    modelo.Id_Condominio = @Model.Id_Condominio;
                }
                modelo.Condominio = $('#txtcondominio').val();
                modelo.Clave = $('#txtclave').val();
                modelo.id_Estado = $('#ddlEstado').val();
                modelo.DemMun = $('#txtdemmun').val();
                modelo.Colonia = $('#txtcolonia').val();
                modelo.Cp = $('#txtcp').val();
                return modelo;
        }
        $(document).ready(function () {
            LlenaSelect('@Url.Action("Select","Estados")', 'ddlEstado');
             $('select').formSelect();
            M.updateTextFields();
        });

    </script>
}

AdminVivienda/Views/Condominio/CondominioGrid.cshtml
@model List<AdminVivienda.DAL.CAT_CONDOMINIO>
@{
    WebGrid grid = new WebGrid(Model);
}
@grid.GetHtml(
            tableStyle: "table table-hover table-responsive",
            alternatingRowStyle: "table-dark",
            mode: WebGridPagerModes.All,
            firstText: "<< Primero",
            previousText: "< Anterior",
            nextText: "Siguiente >",
            lastText: "Último >>", //add next or prev link in webgrid
            columns: grid.Columns(
                grid.Column("Condominio",canSort:true),
                 //grid.Column("Clave",canSort:true),
                 //grid.Column("DemMun",canSort:true),
                 //grid.Column("Colonia",canSort:true),
                 grid.Column(header: "Estatus", canSort: false, style: "", format: (item) => new HtmlString(
                       "<i class='material-icons'>" + (item.Activo ? "check_box" : "check_box_outline_blank") + "</i>")),
                grid.Column(header: "Editar", canSort: false, style: "", format: (item) => new HtmlString(
                       "<a href=" + @Url.Action("Details", new { id = item.Id_Condominio }) + "   class='btn-floating waves-effect waves-light btnComponent' ><i class='material-icons left'>brush</i></a> "))
                            )
                        )  

AdminVivienda/Views/Condominio/Index.cshtml
@section styles{
@*<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">*@
    }
<h3 class="header">@ViewBag.Title</h3>
<hr />
<div class="divControl">
    @*style="display:none"*@
    <div class="row">
        <div class="input-field col s4 m4 l4">
            <label for="txtcondominio">Buscar condominio:</label>
            <input type="text" id="txtcondominio">
        </div>
        <div class="input-field col s4 m4 l4">
            <select id="ddlActivo">
                <option selected="" value="-1">Todos</option>
                <option value="1">Activo</option>
                <option value="0">Inactivo</option>
            </select>
            <label>Estatus:</label>
        </div>
        <div class="col s4 m4 l4">
            <div class="row valign-wrapper">
                <div class="col s10">
                    <button type="button" class="btn-info waves-effect waves-light btn btnComponent"><i class="material-icons left">search</i>Buscar</button>
                </div>
                <div class="col s2">
                    <a href="@Url.Action("Create")" class="waves-effect waves-light btn-floating btnComponent"><i class="material-icons left">add</i></a>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div id="divTableCondominio">

    </div>
</div>
@section scripts{
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
        var _urlGrid = '@Url.Action("Grid")';
        $(document).ready(function () {
            EjecutaAjaxBusqueda();
            $('select').formSelect();
        });
        $(".btn-info").click(function () {
            EjecutaAjaxBusqueda();
        });
        function EjecutaAjaxBusqueda() {
            var modelo = new Object();
            modelo.Condominio = $('#txtcondominio').val();
            modelo.Activo = $('#ddlActivo').val();
            FncExeAjax(_urlGrid, modelo, "POST", false, FncGrid);
        }
        function FncGrid(datos) {
            $('#divTableCondominio').html(datos);
            $('#divControl').fadeIn();
        }
    </script>
}